# Generated by Django 4.0.1 on 2022-01-13 08:47

import django.core.validators
from django.db import migrations, models
import excel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=excel.models.get_excel_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xls', 'xlsx'))], verbose_name='путь')),
                ('processing_stop', models.DateTimeField(blank=True, null=True, verbose_name='окончание обработки')),
                ('processing_status', models.SmallIntegerField(choices=[(0, 'Загружено'), (1, 'Обрабатывается'), (2, 'Обработано')], default=0, verbose_name='статус обработки')),
                ('processing_result', models.CharField(blank=True, max_length=255, verbose_name='результат обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'файл Excel',
                'verbose_name_plural': 'файлы Excel',
                'ordering': ('created_at',),
            },
        ),
    ]
